version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: newtwitter
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"


api:
  build: ./backend/app
  command: python manage.py runserver 0.0.0.0:8000
  environment:
    AMBIENTE: producao
    DEPURACAO: "true"
    PG_NOME: newtwitter
    PG_USUARIO: postgres
    PG_SENHA: postgres
    PG_HOST: db
    PG_PORTA: 5432
    SEGREDO_DJANGO: dev-secret
  volumes:
    - ./backend/app:/app
  depends_on:
    - db
  ports:
    - "8000:8000"


frontend:
  build: ./frontend
  environment:
    - VITE_API_URL=http://localhost:8000/api
  volumes:
    - ./frontend:/usr/src/app
  ports:
    - "5173:5173"


nginx:
  build: ./backend/docker/nginx
  volumes:
    - ./backend/app/static:/app/static
    - ./backend/app/midia:/app/midia
  ports:
    - "8080:80"
  depends_on: 
    - api


volumes:
  pgdata: