services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: newtwitter
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"


  api:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      AMBIENTE: desenvolvimento
      DEPURACAO: "true"
      PG_NOME: newtwitter
      PG_USUARIO: postgres
      PG_SENHA: postgres
      PG_HOST: db
      PG_PORTA: 5432
      SEGREDO_DJANGO: dev-secret
    volumes:
      - ./backend:/app
    depends_on:
      - db
    ports:
      - "8000:8000"


  frontend:
    image: node:20-alpine
    working_dir: /usr/src/app
    command: sh -c "npm install && npm run dev -- --host --port 5173"
    environment:
      - VITE_API_URL=http://localhost:8080/api
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "5173:5173"


  nginx: 
    image: nginx:1.27-alpine
    volumes:
      - ./backend/docker/nginx/nginx.conf:/etc/nginx/conf.d/app.conf:ro
      - /dev/null:/etc/nginx/conf.d/default.conf:ro
      - ./backend/static:/app/static
      - ./backend/midia:/app/midia      
    ports:
      - "8080:80"
    depends_on: 
      - api


volumes:
  pgdata: