# Generated by Django 5.2.5 on 2025-08-20 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("postagens", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="comentario",
            name="autor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="curtida",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="postagem",
            name="autor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="curtida",
            name="postagem",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="curtidas",
                to="postagens.postagem",
            ),
        ),
        migrations.AddField(
            model_name="comentario",
            name="postagem",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comentarios",
                to="postagens.postagem",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="curtida",
            unique_together={("usuario", "postagem")},
        ),
    ]
