# Generated by Django 5.2.5 on 2025-09-08 21:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postagens", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="curtida",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="curtida",
            constraint=models.UniqueConstraint(
                fields=("usuario", "postagem"), name="unico_like_usuario_postagem"
            ),
        ),
    ]
