# Generated by Django 5.2.5 on 2025-08-20 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("relacionamentos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="seguir",
            name="seguido",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seguido_por",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="seguir",
            name="seguidor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="segue",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="seguir",
            constraint=models.CheckConstraint(
                condition=models.Q(("seguidor", models.F("seguido")), _negated=True),
                name="não_seguir_a_si_mesmo",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="seguir",
            unique_together={("seguidor", "seguido")},
        ),
    ]
